// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MossWPF.Data;

#nullable disable

namespace MossWPF.Data.Migrations
{
    [DbContext(typeof(MossDbContext))]
    partial class MossDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("MossWPF.Domain.Models.FilePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstFilePercentageScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesMatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondFilePercentageScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstFileId");

                    b.HasIndex("SecondFileId");

                    b.ToTable("FilesPairs");
                });

            modelBuilder.Entity("MossWPF.Domain.Models.MatchingPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilePairId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstFileLines")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedLines")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondFileLines")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePairId");

                    b.ToTable("MatchingPassages");
                });

            modelBuilder.Entity("MossWPF.Domain.Models.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MossWPF.Domain.Models.FilePair", b =>
                {
                    b.HasOne("MossWPF.Domain.Models.SubmissionFile", "FirstFile")
                        .WithMany()
                        .HasForeignKey("FirstFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MossWPF.Domain.Models.SubmissionFile", "SecondFile")
                        .WithMany()
                        .HasForeignKey("SecondFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstFile");

                    b.Navigation("SecondFile");
                });

            modelBuilder.Entity("MossWPF.Domain.Models.MatchingPassage", b =>
                {
                    b.HasOne("MossWPF.Domain.Models.FilePair", "FilePair")
                        .WithMany()
                        .HasForeignKey("FilePairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilePair");
                });
#pragma warning restore 612, 618
        }
    }
}
